### ISSUE TITLE
Duplicate assets and asset groups should result in an error

### ISSUE THREAD

**Issue by benarmston** [alces-flight/flight-asset-cli#1]
Flight Center does not (yet?) prevent multiple assets for a component from having the same name.

`flight-asset` does the right thing and refuses to create an asset with a duplicate name.  However, there are ways of creating assets outside of `flight-asset`, so this is not sufficient to prevent duplicate assets.

If there are duplicate assets a request such as `flight asset update-asset node01 --support-type managed` is ill-defined.  `flight-asset` should check for uniqueness and refuse to update the asset if it is not uniquely named.

There is a similar issue for groups, when listing the assets in a group.  If there are multiple groups with the same name for the component, the results are ill-defined.  Instead an error should be reported.

**Comment by WilliamMcCumstie** [comment]
wip

**Comment by WilliamMcCumstie** [comment]
Fixed in the `0.3.0` release
