### ISSUE TITLE
Remove use of dummy-group

### ISSUE THREAD

**Issue by benarmston** [alces-flight/flight-asset-cli#11]
The initial version of this tool worked around a bug in the FC asset creation API by sometimes creating assets in a "dummy group" and then removing them.

This workaround is confusing for a couple of reasons.

1. It results in the dummy group being visible in the FC UI.  Which is confusing to anyone using FC who doesn't also have knowledge of this tool.
2. The presence of the dummy group in the configuration is confusing to engineers without a knowledge of the bug and its workaround.

Of course, a prerequisite is that the FC API supports creating groups without assigning them to a group.  @benarmston is to investigate and fix that as required.

**Comment by WilliamMcCumstie** [comment]
This will be initially a hidden config parameter until the corresponding API change has been made

**Comment by benarmston** [comment]
The underlying bug with the FC API does not exist on current staging or production deployments.  We can safely remove any workaround in place.
