### ISSUE TITLE
Better defaults for configuration values

### ISSUE THREAD

**Issue by benarmston** [alces-flight/flight-asset-cli#14]
The defaults for the configuration values that are not managed by `flight asset configure` should be changed to better support the tool being ran by non-root users.

The defaults should be as follows:

```
:base_url: https://center.alces-flight.com/api
:api_prefix: v1
:log_path: ~/.cache/flight/asset/flight-asset.log
:log_level: error
:tmp_path: /tmp/flight-asset
:credentials_file: ~/.config/flight/asset/credentials.yml
```

**Comment by WilliamMcCumstie** [comment]
I'm a tad confused about these defaults, should the defaults not fallback onto `XDG`?

Something along the lines:
```
log_path: ${XDG_CACHE_HOME}/flight/asset-cli/flight-asset.log
credentials_file: ${XDG_CONFIG_HOME}/flight/asset/credentials.yml
... etc ...
```

**Comment by benarmston** [comment]
Yes. They should be using the `XDG_*` variables if they are set.  If they are not set, the default value for that environment variable should be used.  The default values being `${HOME}/.cache` and `${HOME}/.config`.

**Comment by WilliamMcCumstie** [comment]
This was implemented across various commits, will create refs in the future

**Comment by mjtko** [comment]
The `credentials.yml` file is created in the wrong place, i.e. it ends up at `~/.local/share/flight/asset-cli/credentials.yaml` ("`XDG_DATA`") rather than `~/.config/flight/asset/credentials.yml` ("`XDG_CONFIG`").

**Comment by mjtko** [comment]
Spotted that this is not the right issue to reopen. Bit confusing what's where atm.
