### ISSUE TITLE
Support per-user configuration values

### ISSUE THREAD

**Issue by benarmston** [alces-flight/flight-asset-cli#15]
In addition to the global configuration file for static configuration values (#12) support should be added for a per-user configuration file for the static configuration.  This configuration file should be located at `~/.config/flight/asset/config.yml`.

The values in the per-user configure file, override those in the global configuration file.  If any values are missing from both, they should default to the values given in #14.

**Comment by WilliamMcCumstie** [comment]
I'm not sure this feature is required if we obey `XDG_{DATA || CONFIG}_HOME` for the `credentials_file` and `XDG_LOG_HOME`.

Combine that with "flight_asset_CONFIG_PATH" env var (find ref) and the user already has multiple configuration options.

**Comment by WilliamMcCumstie** [comment]
Alternatively, we could not implement `${flight_asset_ROOT}/etc/config.yml` as mentioned in the working doc, and use `XDG` to preform the config-cascade

**Comment by benarmston** [comment]
I've also come to the conclusion that this isn't required / we don't have a concrete use-case for it at the moment.  The defaults given in #14 should be sufficient to meet our needs.

If we discover a use-case we can reopen this.
