### ISSUE TITLE
When listing assets it should be possible to filter for only decommissioned or not-decommissioned assets

### ISSUE THREAD

**Issue by benarmston** [alces-flight/flight-asset-cli#2]
Add a command line option to the `list-assets` command to filter for the shown assets based on whether they've been decommissioned.

Perhaps `flight asset list-assets --decommissioned <false|true|both>`. Defaulting to `both`.

**Comment by WilliamMcCumstie** [comment]
WIP

**Comment by WilliamMcCumstie** [comment]
Fixed in the `0.3.1` release
