### ISSUE TITLE
Limit quantity of data that can be pumped through info field by default

### ISSUE THREAD

**Issue by benarmston** [alces-flight/flight-asset-cli#23]
Add limit to quantity of data that can be pumped through info field by default. Let’s limit it to 32KiB by default.

Make this a config file value.  It should not be managed by the `configure` command.  It should be overridable in the global and per-user config files.

**Comment by WilliamMcCumstie** [comment]
I don't think a blanket limit is the best approach. The majority of the fields that are displayed are fixed values (`yes/no`, `support_type`, etc ..) or names or things. IMO it's safe to assume the names are reasonable lengths. The server should already reject bogus names (?).

This leaves the `additional information` for an `asset` which could grow excessively large. Currently the info is returned from `show`, `update`, `create`, `edit`, etc which is mostly noise. Instead I think all these commands should display the "info size".

Then a new `view-asset` command can be added as a companion to `edit-asset`. It would open the file up according to the `$PAGER` env var (similar to `$EDITOR` for edit). This would bypass the need for a size limit

NOTE: `TTY::Table` does a pretty good job at formatting tables, but it can stumble over extremely wide inputs. This can cause issues with editors which wrap text without adding a line break.

**Comment by mjtko** [comment]
Don't think this is asking for/I asked for a blanket limit -- just want to limit what can go in the `additional information` field.  Having a limit prevents silly accidents.

**Comment by benarmston** [comment]
Hopefully this clarifies the issue:

 - The limit is to apply only to the `additional information` (a.k.a., `info`).

 - The limit should be set in the configuration file and default to 32KiB.  The configuration file used is the one *not* managed by the `configure` command.

 - If an attempt to send a larger amount of data in the `additional information` field is made, the tool should not make the request; exit with an error; and inform the user that they can change the value in the configuration file.

 - We don't envision silly accidents being made on any other fields, so they do not need to have a limit applied.

**Comment by benarmston** [comment]
For further clarification this issue is about limiting the size of `POST` and `PUT` request bodies, not about limiting the size of data being displayed by the CLI tool.

**Comment by WilliamMcCumstie** [comment]
Apologies it appears we are discussing different issues. There is a commit on it's way that implements a size limit as requested.

The secondary issue is concerning widths and will be addressed separately
