### ISSUE TITLE
Show the possible values for the `support_type`

### ISSUE THREAD

**Issue by WilliamMcCumstie** [alces-flight/flight-asset-cli#30]
This was mentioned in #20 but needs to be handled as a separate issue.

The two option on how this could work:
1. Set the types as a configuration parameter with sensible defaults. This will allow supporting additional types without a code base change.

2. Dynamically set and cache the current valid types via a network request.

**Comment by mjtko** [comment]
How about option (3) -- hard code the three types. 😄

**Comment by benarmston** [comment]
I thought there were four valid types: `managed`, `advice`, `collaborative`, `inherit`.  Was there one of these you didn't want @mjtko ?

**Comment by mjtko** [comment]
Ah, four types then, yes -- I'd forgotten about `collaborative`!
