### ISSUE TITLE
Slow to do any asset operation if there are large numbers of assets

### ISSUE THREAD

**Issue by mjtko** [alces-flight/flight-asset-cli#35]
Looks like this might be something to do with having to load all assets each time.

On the component I was trying to manipulate assets for there are ~800 assets and this causes `flight asset list` to take ~63 seconds to complete.

Similar times are seen for `flight asset move`.

Needs improving, cos I want to move several hundred assets. :-)

**Comment by benarmston** [comment]
Fixed in 0.5.0.
