### ISSUE TITLE
Support creating and updating asset groups

### ISSUE THREAD

**Issue by benarmston** [alces-flight/flight-asset-cli#6]
We should support creating and updating asset groups similar to how we update and create assets.

Note: asset *categories* are shared across all components currently.  It is best that we don't support creating or updating them via a tool designed to manage a single component.

**Comment by WilliamMcCumstie** [comment]
WIP

**Comment by WilliamMcCumstie** [comment]
The `create-group` command has been added in `0.3.0`. There is no `update-group` command as there are no applicable fields to update. Currently all the other "update/PATCH" actions are implemented as `(re/de)commission-*` and `move-*`.

The `update-asset` command only modifies the support type.
