### ISSUE TITLE
Support un-decommissioning an asset

### ISSUE THREAD

**Issue by benarmston** [alces-flight/flight-asset-cli#7]
An engineer may accidentally decommission the wrong asset, perhaps an attempt to decommission `node01` resulted in `node10` being wrongly decommissioned.  We should provide a command to undecommission an asset.  Perhaps, this should be called `commission` or perhaps `undecommission`?

**Comment by WilliamMcCumstie** [comment]
WIP

**Comment by WilliamMcCumstie** [comment]
Implemented as `recommission-asset` in version `0.3.0`
